log4cplus.rootLogger=INFO, ALL_MSGS, STDOUT
# TRACE DEBUG INFO WARN ERROR FATAL OFF
log4cplus.appender.STDOUT=log4cplus::ConsoleAppender
log4cplus.appender.STDOUT.layout=log4cplus::PatternLayout
log4cplus.appender.STDOUT.layout.ConversionPattern =%D{%Y-%m-%d %H:%M:%S.%q} %5p %5t [%22b:%-4L] --- %m%n

log4cplus.appender.ALL_MSGS=log4cplus::RollingFileAppender
log4cplus.appender.ALL_MSGS.File=./logs/all.log
log4cplus.appender.ALL_MSGS.MaxFileSize=100MB
log4cplus.appender.ALL_MSGS.layout=log4cplus::PatternLayout
log4cplus.appender.ALL_MSGS.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S.%q} %5p %5t [%22b:%-4L] --- %m%n
log4cplus.appender.ALL_MSGS.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.ALL_MSGS.filters.1.LogLevelMin=TRACE
log4cplus.appender.ALL_MSGS.filters.1.LogLevelMax=FATAL
log4cplus.appender.ALL_MSGS.filters.1.AcceptOnMatch=true
log4cplus.appender.ALL_MSGS.filters.2=log4cplus::spi::DenyAllFilter
