#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "grpc.pb.h"

namespace grpc
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void api(CommonRequest *request, CommonResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using apiDone = std::function<void (CommonResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void api(const CommonRequest *req, apiDone done);
	void api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> async_api(const CommonRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_api_task(apiDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void api(const CommonRequest *req, apiDone done);
	void api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> async_api(const CommonRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_api_task(apiDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void api(const CommonRequest *req, apiDone done);
	void api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> async_api(const CommonRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_api_task(apiDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void api(const CommonRequest *req, apiDone done);
	void api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> async_api(const CommonRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_api_task(apiDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void api(const CommonRequest *req, apiDone done);
	void api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> async_api(const CommonRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_api_task(apiDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("grpc")
{
	this->srpc::RPCService::add_method("api",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::api);
		});
}
inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("grpc")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("grpc")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::api(const CommonRequest *req, apiDone done)
{
	auto *task = this->create_rpc_client_task("api", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_api(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> SRPCClient::async_api(const CommonRequest *req)
{
	using RESULT = std::pair<CommonResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CommonResponse>("api", srpc::RPCAsyncFutureCallback<CommonResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_api_task(apiDone done)
{
	return this->create_rpc_client_task("api", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("grpc")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("grpc")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::api(const CommonRequest *req, apiDone done)
{
	auto *task = this->create_rpc_client_task("api", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_api(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_api(const CommonRequest *req)
{
	using RESULT = std::pair<CommonResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CommonResponse>("api", srpc::RPCAsyncFutureCallback<CommonResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_api_task(apiDone done)
{
	return this->create_rpc_client_task("api", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("grpc")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("grpc")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::api(const CommonRequest *req, apiDone done)
{
	auto *task = this->create_rpc_client_task("api", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_api(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> BRPCClient::async_api(const CommonRequest *req)
{
	using RESULT = std::pair<CommonResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CommonResponse>("api", srpc::RPCAsyncFutureCallback<CommonResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_api_task(apiDone done)
{
	return this->create_rpc_client_task("api", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("grpc")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("grpc")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::api(const CommonRequest *req, apiDone done)
{
	auto *task = this->create_rpc_client_task("/grpc/api", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_api(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> TRPCClient::async_api(const CommonRequest *req)
{
	using RESULT = std::pair<CommonResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CommonResponse>("/grpc/api", srpc::RPCAsyncFutureCallback<CommonResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_api_task(apiDone done)
{
	return this->create_rpc_client_task("/grpc/api", std::move(done));
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("grpc")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("grpc")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::api(const CommonRequest *req, apiDone done)
{
	auto *task = this->create_rpc_client_task("api", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::api(const CommonRequest *req, CommonResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_api(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<CommonResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_api(const CommonRequest *req)
{
	using RESULT = std::pair<CommonResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<CommonResponse>("api", srpc::RPCAsyncFutureCallback<CommonResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_api_task(apiDone done)
{
	return this->create_rpc_client_task("api", std::move(done));
}

} // end namespace grpc

